# Generated by Django 5.0.6 on 2024-12-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_items_user_products_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
    ]
