# Generated by Django 5.0.6 on 2025-01-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_items_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
