# Generated by Django 5.0.6 on 2025-01-06 08:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_items_phone_products_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemgallery",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="items",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
