# Generated by Django 5.0.6 on 2025-01-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_alter_itemgallery_image_alter_items_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="name",
            field=models.CharField(db_index=True, max_length=300),
        ),
    ]
