# Generated by Django 5.0.6 on 2025-01-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_alter_items_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
